### ISSUE TITLE
Ok, i was able to reproduce your issue.  it looks like you switched to use the non-chat (base) version of llama2.  Can you add `-f` to your model name as follows:

### ISSUE THREAD

**Issue by frank-morales2020** [generative-ai-on-aws/generative-ai-on-aws#2]
Ok, i was able to reproduce your issue.  it looks like you switched to use the non-chat (base) version of llama2.  Can you add `-f` to your model name as follows:

```
llm_model_id, llm_model_version = "meta-textgeneration-llama-2-7b-f", "2.*"
```

Once I made that change, then I get a valid response.

Here is the list of llama2 models supported by SageMaker JumpStart currently:

<img width="1106" alt="image" src="https://github.com/generative-ai-on-aws/generative-ai-on-aws/assets/1438064/d2c9685f-817c-43de-95cd-e2b6274af7bc">

Please re-open if you still see the issue.  And thanks for reporting this!

_Originally posted by @cfregly in https://github.com/generative-ai-on-aws/generative-ai-on-aws/issues/1#issuecomment-1869785014_

**Comment by frank-morales2020** [comment]
I used that model ID initially as it is in the one used by the notebook originally. So I reran with your suggestion, and the same error happened.

**error reference** 

#ValueError: Error raised by inference endpoint: An error occurred (ModelError) when calling the InvokeEndpoint operation: Received client error (424) from primary with message "{
#  "code":424,
#  "message":"prediction failure",
#  "error":"can only concatenate str (not \"list\") to str"
#}". See https://us-east-1.console.aws.amazon.com/cloudwatch/home?region=us-east-1#logEventViewer:group=/aws/sagemaker/Endpoints/meta-textgeneration-llama-2-7b-2023-12-18-08-21-44-646 in account  xxxxxxxxxxxx for more information.

**Comment by frank-morales2020** [comment]
I found the solution. The version that works for me is **2.0.4.** I think you should change your notebook exercise for it. 

llm_model_id = 'meta-textgeneration-llama-2-7b-f'
llm_model_version = '2.0.4'
llm_model = JumpStartModel(model_id=llm_model_id, model_version=llm_model_version, role=ROLE_ARN, region='us-east-1')
#modified by frankmorales
llm_predictor = llm_model.deploy(accept_eula=True)

My correct notebook is below: 
https://github.com/frank-morales2020/generative-ai-on-aws-book/blob/main/01_langchain_llama2_sagemaker.ipynb

Thank you for your assistance, and happy holidays. 

Frank

**Comment by cfregly** [comment]
btw, i undid a lot of your `payload` code and just reverted to `query="..."`  that might be a difference, as well.

<img width="845" alt="image" src="https://github.com/generative-ai-on-aws/generative-ai-on-aws/assets/1438064/f103456c-81ae-4500-84dd-f3ff3abfca2d">

**Comment by frank-morales2020** [comment]
In my final version below, I cleaned up some cells. look below 

https://github.com/frank-morales2020/generative-ai-on-aws-book/blob/main/01_langchain_llama2_sagemaker.ipynb

**Comment by cfregly** [comment]
nice!!
