### ISSUE TITLE
ModuleNotFoundError: No module named 'optimum' in llama2 sagemaker finetuning notebook

### ISSUE THREAD

**Issue by ddahlmeier** [generative-ai-on-aws/generative-ai-on-aws#3]
I am following the example for finetuning llama-2 on AWS Sagemaker with Huggingface: https://github.com/generative-ai-on-aws/generative-ai-on-aws/blob/main/05_finetune/02_fine_tune_dolly_llama2_sagemaker_cluster.ipynb

Everythink seems to be going fine until I submit the training job. I get an "No module named 'optimum'" error

```
# define a data input dictonary with our uploaded s3 uris
data = {'training': training_input_path}

# starting the train job with our uploaded datasets as input
huggingface_estimator.fit(data, wait=True)

---
Using provided s3_resource
2023-12-31 10:38:26 Starting - Starting the training job...
2023-12-31 10:38:41 Starting - Preparing the instances for training......
2023-12-31 10:39:46 Downloading - Downloading input data...
2023-12-31 10:40:06 Downloading - Downloading the training image...........................
2023-12-31 10:44:52 Training - Training image download completed. Training in progress.

[lots of log output here]

File "/opt/ml/code/run_clm.py", line 11, in <module>
    from optimum.neuron import NeuronHfArgumentParser as HfArgumentParser
ModuleNotFoundError: No module named 'optimum'
2023-12-31 10:45:53,724 sagemaker-training-toolkit INFO     Waiting for the process to finish and give a return code.
2023-12-31 10:45:53,724 sagemaker-training-toolkit INFO     Done waiting for a return code. Received 1 from exiting process.
2023-12-31 10:45:53,724 sagemaker-training-toolkit ERROR    Reporting training FAILURE
2023-12-31 10:45:53,724 sagemaker-training-toolkit ERROR    ExecuteUserScriptError:
ExitCode 1
ErrorMessage "ModuleNotFoundError: No module named 'optimum'"
Command "/opt/conda/bin/python3.10 run_clm.py --dataset_path /opt/ml/input/data/training --epochs 3 --lr 0.0002 --model_id NousResearch/Llama-2-7b-hf --per_device_train_batch_size 1"
2023-12-31 10:45:53,724 sagemaker-training-toolkit ERROR    Encountered exit_code 1

2023-12-31 10:46:15 Uploading - Uploading generated training model
2023-12-31 10:46:15 Failed - Training job failed
```

The optimum library is loaded in the 'run_clm.py' script in scripts/run_clm.py
```
from optimum.neuron import NeuronHfArgumentParser as HfArgumentParser
from optimum.neuron import NeuronTrainer as Trainer
from optimum.neuron import NeuronTrainingArguments as TrainingArguments
from optimum.neuron.distributed import lazy_load_for_parallelism
```

According to the HF website it should be pre-installed in HF DLC images. Maybe I am just using the wrong image when submitting the job but I could not find the exact error source. 

https://huggingface.co/docs/optimum-neuron/guides/sagemaker

**Comment by cfregly** [comment]
Will look into this today. Thanks for reporting this!

**Comment by ddahlmeier** [comment]
I realised that I forgot the requirements.txt files in scripts. I added the file and added the line 'optimum-neuron' to requirements.txt.

Now training starts but terminates with this error

```
2023-12-31 15:28:28 Starting - Starting the training job...
2023-12-31 15:28:42 Starting - Preparing the instances for training......
2023-12-31 15:29:56 Downloading - Downloading input data.........
2023-12-31 15:31:11 Downloading - Downloading the training image.........
2023-12-31 15:32:51 Training - Training image download completed. Training in progress.....
[..]
run_clm.py: error: argument --lr_scheduler_type: invalid choice: '0.0002' (choose from 'linear', 'cosine', 'cosine_with_restarts', 'polynomial', 'constant', 'constant_with_warmup', 'inverse_sqrt', 'reduce_lr_on_plateau')
```

It seems that the learning rate argument ends up being passed to the learning rate scheduler for some strange reason

**Comment by cfregly** [comment]
Can you compare the entire output of your run with the output in the original notebook (successful run)?  And keep an eye on the parameters.

did you make any other changes?

if you run the original notebook, the requirements.txt and learning rate should all be specified correctly.

Thanks!

**Comment by ddahlmeier** [comment]
I checked out the repo (instead of manually copying files) and re-ran the entire notebook without any changes except making the dataset smaller (which should not matter) and changing the instance type to ml.g5.4xlarge. 

I see the same behaviour: I get the same error that optimum is not installed
```
ErrorMessage "ModuleNotFoundError: No module named 'optimum'"
```

When I add otimum-neuron to requirements. txt I get the lr_scheduler error again

```
run_clm.py: error: argument --lr_scheduler_type: invalid choice: '0.0002' (choose from 'linear', 'cosine', 'cosine_with_restarts', 'polynomial', 'constant', 'constant_with_warmup', 'inverse_sqrt', 'reduce_lr_on_plateau')
```

Very strange. In particular, I am able to run the example using sagemaker jumpstart (
05_finetune/03_fine_tune_dolly_llama2_sagemaker_jumpstart.ipynb) without getting this error

**Comment by cfregly** [comment]
ok, i think i figured out what's going on here.  I believe the notebook should refer to `train.py` instead of `run_clm.py`.  

We renamed the .py file, but may not have updated the notebook.

Need to review in the morning, but that's my current theory.

Thanks for reporting this!

**Comment by ddahlmeier** [comment]
I changed the script name to train.py. Now the training loads but fails with a "ErrorMessage "NotImplementedError: Cannot copy out of meta tensor; no data!" error which can happen when the model gets loaded to CPU because of insufficient GPU memory. I will look into this more but I got the jumpstart example working now, so this is not so urgent

The error message is below

[more message here]
Loading checkpoint shards: 100%|██████████| 3/3 [00:10<00:00,  3.42s/it]
Loading checkpoint shards: 100%|██████████| 3/3 [00:10<00:00,  3.62s/it]
Downloading generation_config.json:   0%|          | 0.00/179 [00:00<?, ?B/s]
Downloading generation_config.json: 100%|██████████| 179/179 [00:00<00:00, 1.49MB/s]
╭───────────────────── Traceback (most recent call last) ──────────────────────╮
│ /opt/ml/code/train.py:261 in <module>                                        │
│                                                                              │
│   258                                                                        │
│   259                                                                        │
│   260 if __name__ == "__main__":                                             │
│ ❱ 261 │   main()                                                             │
│                                                                              │
│ /opt/ml/code/train.py:257 in main                                            │
│                                                                              │
│   254                                                                        │
│   255 def main():                                                            │
│   256 │   args = parse_arge()                                                │
│ ❱ 257 │   training_function(args)                                            │
│   258                                                                        │
│   259                                                                        │
│   260 if __name__ == "__main__":                                             │
│                                                                              │
│ /opt/ml/code/train.py:212 in training_function                               │
│                                                                              │
│   209 │   )                                                                  │
│   210 │                                                                      │
│   211 │   # Create Trainer instance                                          │
│ ❱ 212 │   trainer = Trainer(                                                 │
│   213 │   │   model=model,                                                   │
│   214 │   │   args=training_args,                                            │
│   215 │   │   train_dataset=dataset,                                         │
│                                                                              │
│ /opt/conda/lib/python3.10/site-packages/transformers/trainer.py:498 in       │
│ __init__                                                                     │
│                                                                              │
│    495 │   │   self.tokenizer = tokenizer                                    │
│    496 │   │                                                                 │
│    497 │   │   if self.place_model_on_device and not getattr(model, "is_load │
│ ❱  498 │   │   │   self._move_model_to_device(model, args.device)            │
│    499 │   │                                                                 │
│    500 │   │   # Force n_gpu to 1 to avoid DataParallel as MP will manage th │
│    501 │   │   if self.is_model_parallel:                                    │
│                                                                              │
│ /opt/conda/lib/python3.10/site-packages/transformers/trainer.py:740 in       │
│ _move_model_to_device                                                        │
│                                                                              │
│    737 │   │   self.callback_handler.remove_callback(callback)               │
│    738 │                                                                     │
│    739 │   def _move_model_to_device(self, model, device):                   │
│ ❱  740 │   │   model = model.to(device)                                      │
│    741 │   │   # Moving a model to an XLA device disconnects the tied weight │
│    742 │   │   if self.args.parallel_mode == ParallelMode.TPU and hasattr(mo │
│    743 │   │   │   model.tie_weights()                                       │
│                                                                              │
│ /opt/conda/lib/python3.10/site-packages/transformers/modeling_utils.py:1896  │
│ in to                                                                        │
│                                                                              │
│   1893 │   │   │   │   " model has already been set to the correct devices a │
│   1894 │   │   │   )                                                         │
│   1895 │   │   else:                                                         │
│ ❱ 1896 │   │   │   return super().to(*args, **kwargs)                        │
│   1897 │                                                                     │
│   1898 │   def half(self, *args):                                            │
│   1899 │   │   # Checks if the model has been loaded in 8-bit                │
│                                                                              │
│ /opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py:1145 in   │
│ to                                                                           │
│                                                                              │
│   1142 │   │   │   │   │   │   │   non_blocking, memory_format=convert_to_fo │
│   1143 │   │   │   return t.to(device, dtype if t.is_floating_point() or t.i │
│   1144 │   │                                                                 │
│ ❱ 1145 │   │   return self._apply(convert)                                   │
│   1146 │                                                                     │
│   1147 │   def register_full_backward_pre_hook(                              │
│   1148 │   │   self,                                                         │
│                                                                              │
│ /opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py:797 in    │
│ _apply                                                                       │
│                                                                              │
│    794 │                                                                     │
│    795 │   def _apply(self, fn):                                             │
│    796 │   │   for module in self.children():                                │
│ ❱  797 │   │   │   module._apply(fn)                                         │
│    798 │   │                                                                 │
│    799 │   │   def compute_should_use_set_data(tensor, tensor_applied):      │
│    800 │   │   │   if torch._has_compatible_shallow_copy_type(tensor, tensor │
│                                                                              │
│ /opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py:797 in    │
│ _apply                                                                       │
│                                                                              │
│    794 │                                                                     │
│    795 │   def _apply(self, fn):                                             │
│    796 │   │   for module in self.children():                                │
│ ❱  797 │   │   │   module._apply(fn)                                         │
│    798 │   │                                                                 │
│    799 │   │   def compute_should_use_set_data(tensor, tensor_applied):      │
│    800 │   │   │   if torch._has_compatible_shallow_copy_type(tensor, tensor │
│                                                                              │
│ /opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py:797 in    │
│ _apply                                                                       │
│                                                                              │
│    794 │                                                                     │
│    795 │   def _apply(self, fn):                                             │
│    796 │   │   for module in self.children():                                │
│ ❱  797 │   │   │   module._apply(fn)                                         │
│    798 │   │                                                                 │
│    799 │   │   def compute_should_use_set_data(tensor, tensor_applied):      │
│    800 │   │   │   if torch._has_compatible_shallow_copy_type(tensor, tensor │
│                                                                              │
│ /opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py:797 in    │
│ _apply                                                                       │
│                                                                              │
│    794 │                                                                     │
│    795 │   def _apply(self, fn):                                             │
│    796 │   │   for module in self.children():                                │
│ ❱  797 │   │   │   module._apply(fn)                                         │
│    798 │   │                                                                 │
│    799 │   │   def compute_should_use_set_data(tensor, tensor_applied):      │
│    800 │   │   │   if torch._has_compatible_shallow_copy_type(tensor, tensor │
│                                                                              │
│ /opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py:797 in    │
│ _apply                                                                       │
│                                                                              │
│    794 │                                                                     │
│    795 │   def _apply(self, fn):                                             │
│    796 │   │   for module in self.children():                                │
│ ❱  797 │   │   │   module._apply(fn)                                         │
│    798 │   │                                                                 │
│    799 │   │   def compute_should_use_set_data(tensor, tensor_applied):      │
│    800 │   │   │   if torch._has_compatible_shallow_copy_type(tensor, tensor │
│                                                                              │
│ /opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py:820 in    │
│ _apply                                                                       │
│                                                                              │
│    817 │   │   │   # track autograd history of `param_applied`, so we have t │
│    818 │   │   │   # `with torch.no_grad():`                                 │
│    819 │   │   │   with torch.no_grad():                                     │
│ ❱  820 │   │   │   │   param_applied = fn(param)                             │
│    821 │   │   │   should_use_set_data = compute_should_use_set_data(param,  │
│    822 │   │   │   if should_use_set_data:                                   │
│    823 │   │   │   │   param.data = param_applied                            │
│                                                                              │
│ /opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py:1143 in   │
│ convert                                                                      │
│                                                                              │
│   1140 │   │   │   if convert_to_format is not None and t.dim() in (4, 5):   │
│   1141 │   │   │   │   return t.to(device, dtype if t.is_floating_point() or │
│   1142 │   │   │   │   │   │   │   non_blocking, memory_format=convert_to_fo │
│ ❱ 1143 │   │   │   return t.to(device, dtype if t.is_floating_point() or t.i │
│   1144 │   │                                                                 │
│   1145 │   │   return self._apply(convert)                                   │
│   1146                                                                       │
╰──────────────────────────────────────────────────────────────────────────────╯
NotImplementedError: Cannot copy out of meta tensor; no data!
2024-01-01 13:03:17,222 sagemaker-training-toolkit INFO     Waiting for the process to finish and give a return code.
2024-01-01 13:03:17,223 sagemaker-training-toolkit INFO     Done waiting for a return code. Received 1 from exiting process.
2024-01-01 13:03:17,223 sagemaker-training-toolkit ERROR    Reporting training FAILURE
2024-01-01 13:03:17,223 sagemaker-training-toolkit ERROR    ExecuteUserScriptError:
ExitCode 1
ErrorMessage "NotImplementedError: Cannot copy out of meta tensor; no data!"
Command "/opt/conda/bin/python3.10 train.py --dataset_path /opt/ml/input/data/training --epochs 1 --lr 0.0002 --merge_weights True --model_id NousResearch/Llama-2-7b-hf --per_device_train_batch_size 2"
2024-01-01 13:03:17,223 sagemaker-training-toolkit ERROR    Encountered exit_code 1

2024-01-01 13:03:35 Uploading - Uploading generated training model
2024-01-01 13:03:35 Failed - Training job failed

**Comment by cfregly** [comment]
Ok, good info.

let me clean all of this up and re-test on the p4d.24x and get this example working again.

great info!  Thanks so much.
