### ISSUE TITLE
NotImplementedError: Cannot copy out of meta tensor; no data!

### ISSUE THREAD

**Issue by ddahlmeier** [generative-ai-on-aws/generative-ai-on-aws#4]
I am following along on this notebook for Llama 2 finetuning. 
https://github.com/generative-ai-on-aws/generative-ai-on-aws/blob/9155632d0c30ae40a0d60240b95495db73b4d7e1/05_finetune/01_fine_tune_dolly_llama2_huggingface.ipynb

I am running a AWS Sagemaker studio with an ml.g5xlarge instance and Sagemaker Distribution 1.2.

All cells execute without error until the training step. I don't make any modifications to the code except for allowing pip to install the latest versions

```
!pip install peft
!pip install accelerate
```

When running the training cell I get the following error

```
# Define training args
output_dir = "./tmp/llama2"
training_args = TrainingArguments(
    output_dir=output_dir,
    per_device_train_batch_size=args.per_device_train_batch_size,
    bf16=args.bf16,  # Use BF16 if available
    learning_rate=args.lr,
    num_train_epochs=args.epochs,
    gradient_checkpointing=args.gradient_checkpointing,
    # logging strategies
    logging_dir=f"{output_dir}/logs",
    logging_strategy="steps",
    logging_steps=10,
    save_strategy="no",
)

# Create Trainer instance
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=lm_dataset,
    data_collator=default_data_collator,
)

# Start training
trainer.train()
```
---------------------------------------------------------------------------
NotImplementedError                       Traceback (most recent call last)
Cell In[10], line 18
      3 training_args = TrainingArguments(
      4     output_dir=output_dir,
      5     per_device_train_batch_size=args.per_device_train_batch_size,
   (...)
     14     save_strategy="no",
     15 )
     17 # Create Trainer instance
---> 18 trainer = Trainer(
     19     model=model,
     20     args=training_args,
     21     train_dataset=lm_dataset,
     22     data_collator=default_data_collator,
     23 )
     25 # Start training
     26 trainer.train()

File /opt/conda/lib/python3.10/site-packages/transformers/trainer.py:499, in Trainer.__init__(self, model, args, data_collator, train_dataset, eval_dataset, tokenizer, model_init, compute_metrics, callbacks, optimizers, preprocess_logits_for_metrics)
    497 # Quantized models doesn't support `.to` operation.
    498 if self.place_model_on_device and not getattr(model, "is_quantized", False):
--> 499     self._move_model_to_device(model, args.device)
    501 # Force n_gpu to 1 to avoid DataParallel as MP will manage the GPUs
    502 if self.is_model_parallel:

File /opt/conda/lib/python3.10/site-packages/transformers/trainer.py:741, in Trainer._move_model_to_device(self, model, device)
    740 def _move_model_to_device(self, model, device):
--> 741     model = model.to(device)
    742     # Moving a model to an XLA device disconnects the tied weights, so we have to retie them.
    743     if self.args.parallel_mode == ParallelMode.TPU and hasattr(model, "tie_weights"):

File /opt/conda/lib/python3.10/site-packages/transformers/modeling_utils.py:1900, in PreTrainedModel.to(self, *args, **kwargs)
   1895     raise ValueError(
   1896         "`.to` is not supported for `4-bit` or `8-bit` models. Please use the model as it is, since the"
   1897         " model has already been set to the correct devices and casted to the correct `dtype`."
   1898     )
   1899 else:
-> 1900     return super().to(*args, **kwargs)

File /opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py:1145, in Module.to(self, *args, **kwargs)
   1141         return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None,
   1142                     non_blocking, memory_format=convert_to_format)
   1143     return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
-> 1145 return self._apply(convert)

File /opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py:797, in Module._apply(self, fn)
    795 def _apply(self, fn):
    796     for module in self.children():
--> 797         module._apply(fn)
    799     def compute_should_use_set_data(tensor, tensor_applied):
    800         if torch._has_compatible_shallow_copy_type(tensor, tensor_applied):
    801             # If the new tensor has compatible tensor type as the existing tensor,
    802             # the current behavior is to change the tensor in-place using `.data =`,
   (...)
    807             # global flag to let the user control whether they want the future
    808             # behavior of overwriting the existing tensor or not.

File /opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py:797, in Module._apply(self, fn)
    795 def _apply(self, fn):
    796     for module in self.children():
--> 797         module._apply(fn)
    799     def compute_should_use_set_data(tensor, tensor_applied):
    800         if torch._has_compatible_shallow_copy_type(tensor, tensor_applied):
    801             # If the new tensor has compatible tensor type as the existing tensor,
    802             # the current behavior is to change the tensor in-place using `.data =`,
   (...)
    807             # global flag to let the user control whether they want the future
    808             # behavior of overwriting the existing tensor or not.

    [... skipping similar frames: Module._apply at line 797 (2 times)]

File /opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py:797, in Module._apply(self, fn)
    795 def _apply(self, fn):
    796     for module in self.children():
--> 797         module._apply(fn)
    799     def compute_should_use_set_data(tensor, tensor_applied):
    800         if torch._has_compatible_shallow_copy_type(tensor, tensor_applied):
    801             # If the new tensor has compatible tensor type as the existing tensor,
    802             # the current behavior is to change the tensor in-place using `.data =`,
   (...)
    807             # global flag to let the user control whether they want the future
    808             # behavior of overwriting the existing tensor or not.

File /opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py:820, in Module._apply(self, fn)
    816 # Tensors stored in modules are graph leaves, and we don't want to
    817 # track autograd history of `param_applied`, so we have to use
    818 # `with torch.no_grad():`
    819 with torch.no_grad():
--> 820     param_applied = fn(param)
    821 should_use_set_data = compute_should_use_set_data(param, param_applied)
    822 if should_use_set_data:

File /opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py:1143, in Module.to.<locals>.convert(t)
   1140 if convert_to_format is not None and t.dim() in (4, 5):
   1141     return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None,
   1142                 non_blocking, memory_format=convert_to_format)
-> 1143 return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)

NotImplementedError: Cannot copy out of meta tensor; no data!
```

I am aware that I am not running a p4d instance as suggested (I could not get the quota yet). if that is the source of the error, is there a workaround to make it work on other instance types?

Thanks very much.

**Comment by ddahlmeier** [comment]
I found this related forum. It seems to be insufficient VRAM. I will wait for a larger AWS instance and try again.
https://github.com/tloen/alpaca-lora/issues/368
```
When loading the model using device_map="auto" on a GPU with insufficient VRAM, Transformers tries to offload the rest of the model onto the CPU/disk. The problem is, the model is being loaded in float16 which is not supported by CPU/disk (neither is 8-bit). So, torch offloads the model as a meta-tensor (no data). In other words, parts of the model are missing.

Solutions:

Using the -g and -r arguments: gives Accelerate a manual config for where it should offload the model. Accelerate takes care of the dtype.
Loading the model using either float32 or bfloat16 should work. Note, I haven't tested this one out myself but it should work.
Using a larger GPU. This prevents offloading in the first place.
```

**Comment by cfregly** [comment]
The next section on PEFT shows some tips on how to use smaller instances to fine tune llama2.
