### ISSUE TITLE
Hard coded prompt instruction "What is the best way to deploy a generative model on AWS?"  in finetuning example

### ISSUE THREAD

**Issue by ddahlmeier** [generative-ai-on-aws/generative-ai-on-aws#5]
In the llama 2 fientuning example code in 03_fine_tune_dolly_llama2_sagemaker_jumpstart the prompt in the template is hard coded to "What is the best way to deploy a generative model on AWS?" 

template = {
    "prompt": "What is the best way to deploy a generative model on AWS?",
    "completion": " {response}",
}
with open("template.json", "w") as f:
    json.dump(template, f)

Shouldn't this be filled with whatever is the instruction in each training example?

**Comment by ddahlmeier** [comment]
Similar in the step "Evaluate the pre-trained and fine-tuned model" in the same notebook, the prompt is hard coded. 

Maybe I am missing something but it seems that this completely ignores the values in datapoint


def predict_and_print(datapoint):
    # For instruction fine-tuning, we insert a special key between input and output
    input_output_demarkation_key = "\n\n### Response:\n"

    prompt = "What is the best way to deploy a generative model on AWS?"
    
    payload = {
        #"inputs": template["prompt"].format(
        "inputs": prompt.format(
            instruction=datapoint["instruction"], context=datapoint["context"]
        )
        + input_output_demarkation_key,
        "parameters": {"max_new_tokens": 100},
    }
    inputs.append

**Comment by cfregly** [comment]
i believe you are right, yes.  We will look at this in the morning.  Good catch!

**Comment by cfregly** [comment]
likely needs to be something like this:

```
import json

template = {
    "prompt": "Below is an instruction that describes a task, paired with an input that provides further context. "
    "Write a response that appropriately completes the request.\n\n"
    "### Instruction:\n{instruction}\n\n### Input:\n{context}\n\n",
    "completion": " {response}",
}
with open("template.json", "w") as f:
    json.dump(template, f)
```

**Comment by ddahlmeier** [comment]
Yes that makes sense

**Comment by ddahlmeier** [comment]
There is a file named 
local_data_file = "continued_pretraining.jsonl"

which sounds confusing as the example is about instruction tuning

**Comment by ddahlmeier** [comment]
I changed the template as below and the code worked. 

template = {
    "prompt": "Below is an instruction that describes a task, paired with an input that provides further context. Write a response that appropriately completes the request.\n\n### Instruction:\n{instruction}\n\n### Input:\n{context}\n\n",
    "completion": "{response}",
}
with open("template.json", "w") as f:
    json.dump(template, f)
