### ISSUE TITLE
why you do not use llamaIndex , but you use langchain

### ISSUE THREAD

**Issue by Sandy4321** [generative-ai-on-aws/generative-ai-on-aws#7]
https://github.com/generative-ai-on-aws/generative-ai-on-aws/blob/main/09_rag/01_langchain_llama2_sagemaker.ipynb

why you do not use llamaIndex , but you use langchain

**Comment by cfregly** [comment]
happy to accept pull requests for llamaindex!

**Comment by Sandy4321** [comment]
THEN DO IT
